config/routes.rb
EducateMyGirlProgramApp::Application.routes.draw do
  resources :code_testers
root :to => 'code_testers#index'












end

app/models/code_tester.rb
class CodeTester < ActiveRecord::Base
  attr_accessible :Code, :Title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/code_testers_controller.rb
class CodeTestersController < ApplicationController
  # GET /code_testers
  # GET /code_testers.json
  def index
    @code_testers = CodeTester.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @code_testers }
    end
  end

  # GET /code_testers/1
  # GET /code_testers/1.json
  def show
    @code_tester = CodeTester.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @code_tester }
    end
  end

  # GET /code_testers/new
  # GET /code_testers/new.json
  def new
    @code_tester = CodeTester.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @code_tester }
    end
  end

  # GET /code_testers/1/edit
  def edit
    @code_tester = CodeTester.find(params[:id])
  end

  # POST /code_testers
  # POST /code_testers.json
  def create
    @code_tester = CodeTester.new(params[:code_tester])

    respond_to do |format|
      if @code_tester.save
        format.html { redirect_to @code_tester, notice: 'Code tester was successfully created.' }
        format.json { render json: @code_tester, status: :created, location: @code_tester }
      else
        format.html { render action: "new" }
        format.json { render json: @code_tester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /code_testers/1
  # PUT /code_testers/1.json
  def update
    @code_tester = CodeTester.find(params[:id])

    respond_to do |format|
      if @code_tester.update_attributes(params[:code_tester])
        format.html { redirect_to @code_tester, notice: 'Code tester was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @code_tester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /code_testers/1
  # DELETE /code_testers/1.json
  def destroy
    @code_tester = CodeTester.find(params[:id])
    @code_tester.destroy

    respond_to do |format|
      format.html { redirect_to code_testers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_testers_helper.rb
module CodeTestersHelper
end

app/views/code_testers/_form.html.erb
<%= form_for(@code_tester) do |f| %>
  <% if @code_tester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code_tester.errors.count, "error") %> prohibited this code_tester from being saved:</h2>

      <ul>
      <% @code_tester.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Title %><br />
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :Code %><br />
    <%= f.text_area :Code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/code_testers/edit.html.erb
<h1>Editing code_tester</h1>

<%= render 'form' %>

<%= link_to 'Show', @code_tester %> |
<%= link_to 'Back', code_testers_path %>

app/views/code_testers/index.html.erb
<h1>Innovative Codes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @code_testers.each do |code_tester| %>
  <tr>
    <td><%= code_tester.Title %></td>
    <td><%= code_tester.Code %></td>
    <td><%= link_to 'Show', code_tester %></td>
    <td><%= link_to 'Edit', edit_code_tester_path(code_tester) %></td>
    <td><%= link_to 'Destroy', code_tester, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Code tester', new_code_tester_path %>

app/views/code_testers/new.html.erb
<h1>New code_tester</h1>

<%= render 'form' %>

<%= link_to 'Back', code_testers_path %>

app/views/code_testers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @code_tester.Title %>
</p>

<p>
  <b>Code:</b>
  <html><%= @code_tester.Code %></html>
</p>


<%= link_to 'Edit', edit_code_tester_path(@code_tester) %> |
<%= link_to 'Back', code_testers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EducateMyGirlProgramApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>